### PR TITLE
Limit RocksDB LOG file size

### LINKED ISSUE #183: RocksDB "LOG" statistics file using unnecessary amount of storage.
Every RocksDB bucket used by HiveMQ by default generates a statistics report every 10 minutes, with the amount of 320 buckets in HiveMQ (5 * 64) this effectively means that every 2 seconds a report is generated.

For our use this means a steady storage consumption of 300 MB / day or 10 GB / month.

This stems from the following RocksDB behaviour: https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide (search for "stats_dump_period_sec")

## Expected behavior
Limit on the RocksDB bucket "LOG" file filesize or greatly reduced "stats_dump_period_sec" by default in HiveMQ for the RocksDB buckets.

## Actual behavior
The RocksDB bucket "LOG" file keeps growing infinitely, we so far saw usage of over 30GB just by these LOG files. 

### Steps
- Setup HiveMQ server with default configuration
- Have some basic usage (few messages per minute to make sure the RocksDB is used, the "LOG" file is not written to when the database is not used)

### Reproducer code
N/A

## Details
- Affected HiveMQ CE version(s): 2020.2
- Used JVM version: 11

### PR DESCRIPTION
**Pull request by LBrandl**
**Changes**
Limit RocksDB LOG file size
Resolves #183

### CODE REVIEW

**Review by SgtSilvio — APPROVED** [review]

**Review by Florian-Limpoeck — APPROVED** [review]

**Comment by MicWalter** [comment]
Related issue: #183

**Comment by MicWalter** [comment]
Update: Is currently in **Acceptance Test**

**Comment by MicWalter** [comment]
Can be merged. Changes:
* LOG file can only grow to 500kB
* only two LOG files can exists at one time (older LOG will be deleted)
* statistical information are no longer written into LOG
* buffer size per bucket has been reduced to 64KB (before 1MB)

**Comment by kswen** [comment]
I have tested the latest nightly-build version which downloaded from here: https://hivemq.github.io/nightly-builds/#dependency-block
It seems the issue still remain. The **publish_payload_store** and **retained_messages** folders were occupied 4.3 GB since started hiveMQ service yesterday 5 PM.

**Comment by MicWalter** [comment]
Hi @kswen, 
did you start with a fresh HiveMQ or did you replace the hivemq.jar of your existing setup? 

Second case -> the old LOG files are not removed therefore you still have the old LOG files in your buckets (you can just remove the LOG files)

First case -> should not happen anymore

Can you please show me what is using the disk space in the data/persistence folder (mac/linux command to show disk usage: du -ah)?

Greetings,
Michael

**Comment by kswen** [comment]
Hi @MicWalter ,

I had tried two ways( replace jar file and completely new install), and also removed the old data files. 
here is the **du -ah** result - > [https://paste.in/4hBOBu](https://paste.in/4hBOBu)

**Comment by MicWalter** [comment]
Hi @kswen ,

looking at the result, the LOG files are not going beyond their limit (128k should be acutally 100k, df doesn't show the correct value just the next matching block size):
`128K	../hivemq/hivemq-ce-2020.5/data/persistence/publish_payload_store/040000_R/publish_payload_store_3/LOG`

If you want you could use to verify that the LOG file is not above 100kB: 
`ls -lh /hivemq/hivemq-ce-2020.5/data/persistence/publish_payload_store/040000_R/publish_payload_store_3/`

Reading the bucket I guess your HiveMQ is not idle, therefore the disk size used by the data folder itself is normal.

Greetings,
Michael

**Comment by kswen** [comment]
@MicWalter Thanks! 
I have observed for a few days, yeah, the disk usage has stopped growing. Currently, around 4.4GB.

Thanks again!

**Pull request merged**
